# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160517_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
    ]
