# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20160517_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(default='male', max_length=30, null=True),
        ),
    ]
