# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20160517_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='notbob', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(default='!!!', max_length=30, null=True),
        ),
    ]
