# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20160520_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biography',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture_url',
            field=models.URLField(blank=True, default='http://i.imgur.com/oS5abnv.png', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_sex',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
